// <auto-generated />
using System;
using Fretefy.Test.Infra.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fretefy.Test.Infra.EntityFramework.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20241209020617_AdicionandoRegiaoCidade")]
    partial class AdicionandoRegiaoCidade
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Fretefy.Test.Domain.Entities.Cidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("RegiaoId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("RegiaoId1")
                        .HasColumnType("TEXT");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RegiaoId1");

                    b.ToTable("Cidade");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f5564f08-4951-41c8-a54f-52f7f12c2b03"),
                            Nome = "Rio Branco",
                            RegiaoId = 0,
                            UF = "AC"
                        },
                        new
                        {
                            Id = new Guid("e717cc61-74fe-4c1c-865f-e3835ed763e1"),
                            Nome = "Maceió",
                            RegiaoId = 0,
                            UF = "AL"
                        },
                        new
                        {
                            Id = new Guid("66a1af85-0aec-4c1f-8258-81e2df12df73"),
                            Nome = "Macapá",
                            RegiaoId = 0,
                            UF = "AP"
                        },
                        new
                        {
                            Id = new Guid("5013108e-e32d-4c87-94bc-940d31833c76"),
                            Nome = "Manaus",
                            RegiaoId = 0,
                            UF = "AM"
                        },
                        new
                        {
                            Id = new Guid("0bf3a539-1f30-4537-9a91-f94ec75b4a40"),
                            Nome = "Salvador",
                            RegiaoId = 0,
                            UF = "BA"
                        },
                        new
                        {
                            Id = new Guid("2bab59d1-28ef-4f43-b056-aa2f788c7b46"),
                            Nome = "Fortaleza",
                            RegiaoId = 0,
                            UF = " CE"
                        },
                        new
                        {
                            Id = new Guid("72f9ea41-041e-4db5-aefa-0bd7d2ad1509"),
                            Nome = "Brasília",
                            RegiaoId = 0,
                            UF = "DF"
                        },
                        new
                        {
                            Id = new Guid("6aac1ef7-9f0a-44ed-b960-c84502a62322"),
                            Nome = "Vitória",
                            RegiaoId = 0,
                            UF = "ES"
                        },
                        new
                        {
                            Id = new Guid("211206f4-4d90-4a6d-ae20-3c7e9edd6421"),
                            Nome = "Goiânia",
                            RegiaoId = 0,
                            UF = "GO"
                        },
                        new
                        {
                            Id = new Guid("9a9ff32a-061c-40fb-b882-88b0379a4830"),
                            Nome = "São Luís",
                            RegiaoId = 0,
                            UF = "MA"
                        },
                        new
                        {
                            Id = new Guid("64a56a34-3799-468f-9c10-a59252615aee"),
                            Nome = "Cuiabá",
                            RegiaoId = 0,
                            UF = "MT"
                        },
                        new
                        {
                            Id = new Guid("a44dae46-6690-45ef-82db-903bca33f5ff"),
                            Nome = "Campo Grande",
                            RegiaoId = 0,
                            UF = "MS"
                        },
                        new
                        {
                            Id = new Guid("ec1fd3fa-715c-43cd-b460-cc967e117f96"),
                            Nome = "Belo Horizonte",
                            RegiaoId = 0,
                            UF = "MG"
                        },
                        new
                        {
                            Id = new Guid("ad379298-af00-489d-b886-75b93bcf1718"),
                            Nome = "Belém",
                            RegiaoId = 0,
                            UF = "PA"
                        },
                        new
                        {
                            Id = new Guid("8821e383-58a8-4377-8de7-67de69378f63"),
                            Nome = "João Pessoa",
                            RegiaoId = 0,
                            UF = "PB"
                        },
                        new
                        {
                            Id = new Guid("5d1c4363-ae53-40fc-9036-43041aeb8178"),
                            Nome = "Curitiba",
                            RegiaoId = 0,
                            UF = "PR"
                        },
                        new
                        {
                            Id = new Guid("85fc9352-53ff-45d7-95a6-dc72af30f4b3"),
                            Nome = "Recife",
                            RegiaoId = 0,
                            UF = "PE"
                        },
                        new
                        {
                            Id = new Guid("79bb3022-a15c-4bce-8c44-6dfbabd15a92"),
                            Nome = "Teresina",
                            RegiaoId = 0,
                            UF = "PI"
                        },
                        new
                        {
                            Id = new Guid("006630f4-be19-465e-b2b1-75474aaaa06d"),
                            Nome = "Rio de Janeiro",
                            RegiaoId = 0,
                            UF = "RJ"
                        },
                        new
                        {
                            Id = new Guid("48357057-402a-4209-8fef-426cf2830cae"),
                            Nome = "Natal",
                            RegiaoId = 0,
                            UF = "RN"
                        },
                        new
                        {
                            Id = new Guid("888f8f37-7e0f-4b13-b731-d638eb0dccf8"),
                            Nome = "Porto Alegre",
                            RegiaoId = 0,
                            UF = "RS"
                        },
                        new
                        {
                            Id = new Guid("44987593-612f-4388-adf3-f3054511f9dc"),
                            Nome = "Porto Velho",
                            RegiaoId = 0,
                            UF = "RO"
                        },
                        new
                        {
                            Id = new Guid("b8bf26a8-c9ea-40ab-a07f-5095553a3d62"),
                            Nome = "Boa Vista",
                            RegiaoId = 0,
                            UF = "RR"
                        },
                        new
                        {
                            Id = new Guid("267aa499-8e4a-434f-8a5f-92d79ae1639f"),
                            Nome = "Florianópolis",
                            RegiaoId = 0,
                            UF = "SC"
                        },
                        new
                        {
                            Id = new Guid("3135dd88-5793-4d4a-9e38-1d86b58782b0"),
                            Nome = "São Paulo",
                            RegiaoId = 0,
                            UF = "SP"
                        },
                        new
                        {
                            Id = new Guid("62530888-1c97-4cbe-974b-3cebb746403d"),
                            Nome = "Aracaju",
                            RegiaoId = 0,
                            UF = "SE"
                        },
                        new
                        {
                            Id = new Guid("649427a3-fee3-41f7-96fe-396815612276"),
                            Nome = "Palmas",
                            RegiaoId = 0,
                            UF = "TO"
                        });
                });

            modelBuilder.Entity("Fretefy.Test.Domain.Entities.Regiao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Regiao");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c8a89df5-67bb-4d1f-9348-560126abe092"),
                            Nome = "Sul",
                            Status = true
                        });
                });

            modelBuilder.Entity("Fretefy.Test.Domain.Entities.Cidade", b =>
                {
                    b.HasOne("Fretefy.Test.Domain.Entities.Regiao", null)
                        .WithMany("cidades")
                        .HasForeignKey("RegiaoId1");
                });

            modelBuilder.Entity("Fretefy.Test.Domain.Entities.Regiao", b =>
                {
                    b.Navigation("cidades");
                });
#pragma warning restore 612, 618
        }
    }
}
