// <auto-generated />
using System;
using Fretefy.Test.Infra.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fretefy.Test.Infra.EntityFramework.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20241209020933_AdicionandoRegiaoCidadee")]
    partial class AdicionandoRegiaoCidadee
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Fretefy.Test.Domain.Entities.Cidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("RegiaoId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("RegiaoId1")
                        .HasColumnType("TEXT");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RegiaoId1");

                    b.ToTable("Cidade");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fa4b7c06-a49a-4651-b7dd-125274e5521a"),
                            Nome = "Rio Branco",
                            RegiaoId = 0,
                            UF = "AC"
                        },
                        new
                        {
                            Id = new Guid("8dcd7296-45ae-4252-9527-876f747a7ddc"),
                            Nome = "Maceió",
                            RegiaoId = 0,
                            UF = "AL"
                        },
                        new
                        {
                            Id = new Guid("613a7b8b-2bb3-4b56-aaa7-517dd8fdf1fd"),
                            Nome = "Macapá",
                            RegiaoId = 0,
                            UF = "AP"
                        },
                        new
                        {
                            Id = new Guid("fe095108-1f8e-49bf-8cfc-0903fc6b9712"),
                            Nome = "Manaus",
                            RegiaoId = 0,
                            UF = "AM"
                        },
                        new
                        {
                            Id = new Guid("9deeaeed-96b2-4be2-909a-15111df09211"),
                            Nome = "Salvador",
                            RegiaoId = 0,
                            UF = "BA"
                        },
                        new
                        {
                            Id = new Guid("10a9873d-637e-4c86-830a-94a6f8d3f6df"),
                            Nome = "Fortaleza",
                            RegiaoId = 0,
                            UF = " CE"
                        },
                        new
                        {
                            Id = new Guid("97b91af9-78a3-46f8-b491-3bd731caf53e"),
                            Nome = "Brasília",
                            RegiaoId = 0,
                            UF = "DF"
                        },
                        new
                        {
                            Id = new Guid("80b25ea9-5a16-4cb5-9104-00a500e674d2"),
                            Nome = "Vitória",
                            RegiaoId = 0,
                            UF = "ES"
                        },
                        new
                        {
                            Id = new Guid("4b5ff531-b336-4c79-88f8-74e7ee65c810"),
                            Nome = "Goiânia",
                            RegiaoId = 0,
                            UF = "GO"
                        },
                        new
                        {
                            Id = new Guid("dd436661-e68e-4584-8800-547e8cbdf822"),
                            Nome = "São Luís",
                            RegiaoId = 0,
                            UF = "MA"
                        },
                        new
                        {
                            Id = new Guid("95912187-52d6-4e24-b356-67c9a1951e6a"),
                            Nome = "Cuiabá",
                            RegiaoId = 0,
                            UF = "MT"
                        },
                        new
                        {
                            Id = new Guid("8d014d06-22c8-4419-bc34-ef88e3825743"),
                            Nome = "Campo Grande",
                            RegiaoId = 0,
                            UF = "MS"
                        },
                        new
                        {
                            Id = new Guid("5a784e56-6076-45f0-a167-f55cc9f51e0b"),
                            Nome = "Belo Horizonte",
                            RegiaoId = 0,
                            UF = "MG"
                        },
                        new
                        {
                            Id = new Guid("13f61d65-b080-42bf-8a35-59559ec757b6"),
                            Nome = "Belém",
                            RegiaoId = 0,
                            UF = "PA"
                        },
                        new
                        {
                            Id = new Guid("b29df295-1f28-4e90-8a4c-757ba7755885"),
                            Nome = "João Pessoa",
                            RegiaoId = 0,
                            UF = "PB"
                        },
                        new
                        {
                            Id = new Guid("0d0b0cb0-19ff-4f14-a98e-f8d87fc5305f"),
                            Nome = "Curitiba",
                            RegiaoId = 0,
                            UF = "PR"
                        },
                        new
                        {
                            Id = new Guid("d4c88f15-7394-4303-9894-71dd5eb179e5"),
                            Nome = "Recife",
                            RegiaoId = 0,
                            UF = "PE"
                        },
                        new
                        {
                            Id = new Guid("0a925aa8-2353-4160-a60d-18cbc34d067e"),
                            Nome = "Teresina",
                            RegiaoId = 0,
                            UF = "PI"
                        },
                        new
                        {
                            Id = new Guid("a25f4e4e-13bc-449c-a806-fd6edafa7246"),
                            Nome = "Rio de Janeiro",
                            RegiaoId = 0,
                            UF = "RJ"
                        },
                        new
                        {
                            Id = new Guid("a41ca151-117b-4110-819a-fb725eb7a26f"),
                            Nome = "Natal",
                            RegiaoId = 0,
                            UF = "RN"
                        },
                        new
                        {
                            Id = new Guid("beb550d8-58f1-4966-b6be-b812bafdff1f"),
                            Nome = "Porto Alegre",
                            RegiaoId = 0,
                            UF = "RS"
                        },
                        new
                        {
                            Id = new Guid("9334a098-31f0-4fb1-9142-b18efb9dde95"),
                            Nome = "Porto Velho",
                            RegiaoId = 0,
                            UF = "RO"
                        },
                        new
                        {
                            Id = new Guid("9841e9bc-99b0-46e4-802e-9a194543fa1a"),
                            Nome = "Boa Vista",
                            RegiaoId = 0,
                            UF = "RR"
                        },
                        new
                        {
                            Id = new Guid("b6f82939-93f2-4ec3-80ee-7546ee7a098e"),
                            Nome = "Florianópolis",
                            RegiaoId = 0,
                            UF = "SC"
                        },
                        new
                        {
                            Id = new Guid("d89553b8-495b-401d-886f-3bf1c34760ea"),
                            Nome = "São Paulo",
                            RegiaoId = 0,
                            UF = "SP"
                        },
                        new
                        {
                            Id = new Guid("22b20017-45d1-4a80-a759-14f8f40b6226"),
                            Nome = "Aracaju",
                            RegiaoId = 0,
                            UF = "SE"
                        },
                        new
                        {
                            Id = new Guid("1e417103-8cb9-4477-8205-27b0530bec53"),
                            Nome = "Palmas",
                            RegiaoId = 0,
                            UF = "TO"
                        });
                });

            modelBuilder.Entity("Fretefy.Test.Domain.Entities.Regiao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Regiao");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4c1b4153-640a-4cb3-8644-77e6949dd03a"),
                            Nome = "Sul",
                            Status = true
                        });
                });

            modelBuilder.Entity("Fretefy.Test.Domain.Entities.RegiaoCidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CidadeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RegiaoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RegiaoCidade");
                });

            modelBuilder.Entity("Fretefy.Test.Domain.Entities.Cidade", b =>
                {
                    b.HasOne("Fretefy.Test.Domain.Entities.Regiao", null)
                        .WithMany("cidades")
                        .HasForeignKey("RegiaoId1");
                });

            modelBuilder.Entity("Fretefy.Test.Domain.Entities.Regiao", b =>
                {
                    b.Navigation("cidades");
                });
#pragma warning restore 612, 618
        }
    }
}
